const types = {
  ADD_MUSIC_TO_HISTORIC: 'ADD_MUSIC_TO_HISTORIC',
  NEXT: 'NEXT',
  PREV: 'PREV',
  CHANGE_MUSIC: 'CHANGE_MUSIC',
  TOGGLE_SHUFFLE: 'TOGGLE_SHUFFLE',
  TOGGLE_REPEAT: 'TOGGLE_REPEAT'
}
export default types
